project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Hongda Chen"
  site-url: https://hd_chen.github.io
  favicon: images/site-logo.png
  repo-url: https://github.com/hdchen2025/hd_chen.github.io
  repo-actions: [edit, issue]
  
  # page-footer:
    # left: |
      # [lianxh.cn](https://www.lianxh.cn)<br>
    # right: |
      # Made with [Quarto](https://quarto.org/)<br>
    
  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Research Interest"
        href: books.qmd
      - text: "Running projects"
        href: books.qmd
      - text: "Group Members"
        href: books.qmd    
      - text: "Publications"
        href: publications-english.qmd
      # - text: "Blogs"
      # href: blog.qmd
      # - text: "Codes"
      # href: codes.qmd
      # - text: "中文"
      # href: Chinese.qmd
      #- text: "CV"
      # href: CV.pdf

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细