project:
  type: website
  output-dir: docs
  # 把这些原样复制到发布目录（docs/）
  resources:
    - members.yml           # 现在在根目录
    - data/**               # 若以后改放 data/members.yml 也能被拷贝
    - images/**             # 成员照片等静态资源

website:
  page-navigation: true
  title: "Dr. H. Chen's Group at PUMCH"
  site-url: https://hd_chen.github.io
  favicon: images/site-logo.png

  navbar:
    background: "#A9CCE3"
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Research Interest"
        href: research.qmd
      - text: "Running projects"
        href: Running Projects.qmd
      - text: "Group Members"
        href: members.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Notice"
        href: notice.qmd
  page-footer:
    center: |
      © 2025 Hongda Chen. All rights reserved.
format:
  html:
    theme: styles.scss
    css: 
      - members.css
    toc: true               # 默认开启目录
    toc-position: right
    toc-depth: 3
    grid:
      body-width: 1280px
      margin-width: 200px
      gutter-width: 1.5rem

     