---
title: "Publications"
editor: H. Chen
---

::: callout-note
## Links

> -   **ORCID**: <https://orcid.org/my-orcid?orcid=0000-0001-6171-1162>
> -   **PubMed**: <https://pubmed.ncbi.nlm.nih.gov/?term=(%22Chen%20Hongda%22%5BAuthor%5D)%20AND%20(%22Chinese%20Academy%20of%20Medical%20Sciences%22%5BAffiliation%5D%20OR%20%22Peking%20Union%20Medical%20College%20Hospital%22%5BAffiliation%5D%20OR%20%22German%20Cancer%20Research%20Center%22%5BAffiliation%5D)&sort=date>
:::


## Featured Works
> ### **Evaluation of Cancer Screening Strategies**

- **Chen H**, Li N#, Ren J, Feng X, Lyu Z, Wei L, Li X, Guo L, Zheng Z, Zou S, Zhang Y, Li J, Zhang K, Chen W, Dai M, He J. Participation and yield of a population-based colorectal cancer screening programme in China. *Gut*. 2019;68(8):1450-1457. [Link](https://pubmed.ncbi.nlm.nih.gov/30377193/)
- **Chen H**, Werner S, Brenner H. Fresh vs Frozen Samples and Ambient Temperature Have Little Effect on Detection of Colorectal Cancer or Adenomas by a Fecal Immunochemical Test in a Colorectal Cancer Screening Cohort in Germany. *Clin Gastroenterol Hepatol*. 2017;15(10):1547-1556.e5. [Link](https://pubmed.ncbi.nlm.nih.gov/27793749/) 

> ### **Development of Cancer Screening and Early Detection Biomarkers**

- **Chen H**, Zucknick M, Werner S, Knebel P, Brenner H*. Head-to-Head Comparison and Evaluation of 92 Plasma Protein Biomarkers for Early Detection of Colorectal Cancer in a True Screening Setting. *Clin Cancer Res*. 2015;21(14):3318-26. [Link](https://pubmed.ncbi.nlm.nih.gov/26015516/)
- Zhang Y#, Luo J#, Chen K, Li N, Luo C, Di S, Qin J, Zhang F, **Chen H**, Dai M. Cross-cohort analysis identifies shared gut microbial signatures and validates microbial risk scores for colorectal cancer. *J Transl Med*. 2025 Jun 17;23(1):676. [Link](https://pubmed.ncbi.nlm.nih.gov/40528214/)

> ### **Evaluation of Risk-adapted Colorectal Cancer Screening Stategies**

- **Chen H*, Shi J#, Lu M, Li Y, Du L, Liao X, Wei D, Dong D, Gao Y, Zhu C, Ying R, Zheng W, Yan S, Xiao H, Zhang J, Kong Y, Li F, Zou S, Liu C, Wang H, Zhang Y, Lu B, Luo C, Cai J, Tian J, Miao X, Ding K, Brenner H, Dai M*. Comparison of Colonoscopy, Fecal Immunochemical Test, and Risk-adapted Approach in a Colorectal Cancer Screening Trial (TARGET-C). *Clin Gastroenterol Hepatol*. 2023;21(3):808-818. [Link](https://pubmed.ncbi.nlm.nih.gov/35964896/)
- **Chen H**, Lu M, Liu C, Zou S, Du L, Liao X, Dong D, Wei D, Gao Y, Zhu C, Zhu L, Zheng W, Xiao H, Kong Y, Yin H, Zhou H, Ying R, Wang B, Zhang J, Zhang X, Zhang Q, Zhang X, Zhang Y, Wang H, Guo L, Liu L, Ren J, Shi J, Li N, Miao X, Brenner H, Dai M*. Comparative Evaluation of Participation and Diagnostic Yield of Colonoscopy vs Fecal Immunochemical Test vs Risk-Adapted Screening in Colorectal Cancer Screening: Interim Analysis of a Multicenter Randomized Controlled Trial (TARGET-C). *Am J Gastroenterol*. 2020;115(8):1264-1274. [Link](https://pubmed.ncbi.nlm.nih.gov/32282342/)

> ### **Modelling the Long-term Effect of Cancer Screening**

- Lu B, Luo J, Yan Y, Zhang Y, Luo C, Li N, Zhou Y, Wu D, Dai M*, **Chen H**. Evaluation of long-term benefits and cost-effectiveness of nation-wide colorectal cancer screening strategies in China in 2020–2060: a modelling analysis. *Lancet Reg Health West Pac*. 2024;51:101172. [Link](https://pubmed.ncbi.nlm.nih.gov/39247209/)


### Full Academic Papers Published in English
### 2025
> leading author

1. Guo L#*, Wang L#, Cai L#, Zhang Y#, Feng X#, Zhu C, Gao W, Cardoso R, Yang H, Dai M, Brenner H, **Chen H**. Global Distribution of Colorectal Cancer Staging at Diagnosis: An Evidence Synthesis. *Clin Gastroenterol Hepatol*. 2024 Dec 16:S1542-3565(24)01104-2. [Link](https://pubmed.ncbi.nlm.nih.gov/39694204/)
2. Sun C, Zhang X, Su Z, Yao WH, **Chen H**, Zeng YP. Global, regional and national burdens of atopic dermatitis from 1990 to 2021: a trend analysis from the Global Burden of Disease Study 2021. *J Am Acad Dermatol*. 2025 Jun 19:S0190-9622(25)02369-2.
3. Han J#, Zhang L#, Chen Y#, Zhang Y, Wang L, Cai R, Li M, Dai Y, Dang L, **Chen H**, Zhu L. Global HPV vaccination programs and coverage rates: a systematic review. *EClinicalMedicine*. 2025 Jun 9;84:103290.
4. Chen Y#, Zhang Y#, Yan Y#, Han J#, Zhang L, Cheng X, Lu B, Li N, Luo C, Zhou Y, Song K, Iwasaki M, Dai M, Wu D*, **Chen H**. Global colorectal cancer screening programs and coverage rate estimation: an evidence synthesis. J Transl Med. 2025 Jul 22;23(1):811.
5. Zhang Y#, Luo J#, Chen K, Li N, Luo C, Di S, Qin J, Zhang F, **Chen H**, Dai M. Cross-cohort analysis identifies shared gut microbial signatures and validates microbial risk scores for colorectal cancer. *J Transl Med*. 2025 Jun 17;23(1):676. 
6. Zhou Y#, Li N#, Luo J#, Chen Y, Zhang Y, Dai M, **Chen H**. Participation and Yield in Multiple Rounds of Colorectal Cancer Screening based on Fecal Immunochemical Test: A Systematic Review and Meta-Analysis. *Am J Gastroenterol*. 2025;120(3):524-530. 
7. Zhang Y#, Song K#, Zhou Y#, Chen Y, Cheng X, Dai M, Wu D*, **Chen H**. Accuracy and long-term effectiveness of established screening modalities and strategies in colorectal cancer screening: an umbrella review. *Int J Cancer*. 2025;157(1):126-138.
8. Luo C#, Tian B#, Zhou Y, Luo J, Shang Q, Yu S, Dai M, Li Y*, **Chen H*. Deciphering the Interplay Among Inflammatory Bowel Disease, Gut Microbiota, and Inflammatory Biomarkers in the Risk of Colorectal Cancer. *Mediators Inflamm*. 2025 Mar 8:2025:4967641.
9. Song K#, Luo J#, Zhang Y, Wu D, **Chen H**, Dai M. Gut microbiome mediates the associations between lifestyle factors and risk of colorectal high-risk adenoma: results from a population-based cohort study. mSystems. 2025 Sep 22:e0093325.
10. Song K#, Zhang S#, Luo J, Lu B, Li J, Zhou Y, Chen Y, Zhang Y, Yang A, **Chen H**, Wu D. Risk of Metachronous Advanced Neoplasia After Colonoscopy in Patients With Different Index Findings. *J Gastroenterol Hepatol*. 2025 Aug;40(8):1942-1953.
11. Yan Y#, Luo C#, Chen Y, Cheng X, Luo J, Zhou Y, Li N, Zhang Y, Lu B, He Z, Song K, Wu D, **Chen H**, Dai M. Evaluation of a novel approach for colorectal cancer screening using an intelligent tool (INTEL-PATH CRC): a protocol for a multicentre, real-world, cohort study. BMJ Open. 2025 Jul 18;15(7):e098679.  
> contributting author

1. Li N, Luo C, Chen Y, Cheng X, Luo J, Yan Y, Zhang Y, Lu B, He Z, Song K, Wu D, Tian J, Miao X, **Chen H**, Hu F, Dai M. Identification and validation of blood leukocyte DNA methylation biomarkers for early detection of colorectal neoplasm. Chin Med J (Engl). 2025 Jun 6. doi: 10.1097/CM9.0000000000003681. Epub ahead of print. PMID: 40474333.
2. Cao M, Liufu R, Wang B, Pan W, **Chen H**, Su L, Long Y, Zhou X, Weng L, Du B; Critical Care Clinical Trials Group; China National Critical Care Quality Control Center Group. Population-wise incidence and outcomes of patients requiring invasive and non-invasive mechanical ventilation in China: a nationwide retrospective analysis by age, sex, and comorbidity. Ann Intensive Care. 2025 Aug 14;15(1):120.
3. Huang S, Jia Y, Zhang Y, **Chen H**, Deng C, Fei Y. Effects of glucocorticoid withdrawal on relapse risk in systemic lupus erythematosus: A systematic review and meta-analysis. iScience. 2025 Jun 13;28(7):112875.
4. Yan X, Li X, Chen Y, Ouzhu M, Guo Z, Lyu C, Yang D, **Chen H**, Xie F, Wu D. Health economics evaluation of diagnostic strategies for gastro-oesophageal reflux disease with reflux symptoms in China: a modelling study. BMJ Open. 2025 May 14;15(5):e093108. (IF=2.3) 
5. Li N*, Song K*, **Chen H**, Dai M#. Advance and challenge of DNA methylation as cancer biomarkers for risk stratification, screening and early detection. J Natl Cancer Cent. 2025 Jan 30;5(2):108-112.
6. Lu Z, Chen C, Zhang H, Li B, Liu Y, Guo J, Xu R, Shi K, Ma Q, Zhang M, Cai Y, Huang J, Geng H, Fan L, Ning C, Li Y, Chen S, Tian W, Hu K, Li H, Yang X, Huang C, Wei Y, Zhu X, Li X, Xiong Z, Cai M, Wang X, Zhang S, **Chen H**, Dai M, Chen K, Jin M, Jin M, Zhu Y, Tian J, Miao X. Characterization of cis-regulatory elements and functional variants in colorectal cancer using epigenomics and CRISPRi screenings. Nat Cancer. 2025 Aug 25. doi: 10.1038/s43018-025-01031-z. Epub ahead of print. PMID: 40854986.

### 2024
> leading author

1. Lu B, Luo J, Yan Y, Zhang Y, Luo C, Li N, Zhou Y, Wu D, Dai M*, **Chen H**. Evaluation of long-term benefits and cost-effectiveness of nation-wide colorectal cancer screening strategies in China in 2020–2060: a modelling analysis. *Lancet Reg Health West Pac*. 2024;51:101172.

2. Lu B#, Xu Y#, Li N, Zhou Y, Ma X, Chen Y, Dong R, Zhou X, Dai M, **Chen H**, Weng L, Du B. Overall and geographic pattern of incidence, case fatality and mortality of sepsis among hospitalised non-child cancer patients in China: a national observational study. *Sci Bull (Beijing)*. 2024 Jun 15;69(11):1637-1641.

3. Dai Y#, **Chen H#**, Yu J, Cai J, Lu B, Dai M*, Zhu L. Global and regional trends in the incidence and prevalence of uterine fibroids and attributable risk factors at the national level from 2010 to 2019: A worldwide database study. *Chin Med J (Engl)*. 2024 Nov 5;137(21):2583-2589. 

4. Cai J#, Lu B#, **Chen H#**, Lu M, Zhang Y, Luo C, You L, Dai M, Zhao Y. The impacts of exposure to risk factors during youth on the increasing global trend of early-onset pancreatic cancer. *Public Health*. 2024 Apr;229:65-72. 

5. Zhou Y#, Song K#, Chen Y, Zhang Y, Dai M, Wu D, **Chen H**. Burden of six major types of digestive system cancers globally and in China. *Chin Med J (Engl)*. 2024 Aug 20;137(16):1957-1964. 

6. Luo C, Luo J, Zhang Y, Lu B, Li N, Zhou Y, Chen S, Wu S, Zhang Q, Dai M, **Chen H**. Associations between blood glucose and early- and late-onset colorectal cancer: evidence from two prospective cohorts and Mendelian randomization analyses. *J Natl Cancer Cent*. 2024;4(3):241-248.

7. Song K, He W, Wu Z, Meng J, Tian W, Zheng S, Mu D, Wang R, **Chen H**, Zhu Y, Wu D. Early clinical predictors of infected pancreatic necrosis: a multicentre cohort study. *eGastroenterology*. 2024;2:e100095.  

8. **Chen H#**, Lu B#, Xu Y#, Li N, Zhou Y, Ma X, Chen Y, Dong R, Zhou X, Dai M, Weng L, Du B. Trend in sepsis burden among hospitalized non-child cancer patients in China, 2017–2019: a nationwide cross-sectional study. *Med Plus*. 2024;1(4):100062.

9. **Chen H**, Dai M#. Reply. Clin Gastroenterol Hepatol. 2024 Feb;22(2):433.

10. Yang Z, Zhou Y, Han Z, He K, Zhang Y, Wu D, **Chen H**. The effects of probiotics supplementation on Helicobacter pylori standard treatment: an umbrella review of systematic reviews with meta-analyses. Sci Rep. 2024 May 2;14(1):10069.

    

    > contributting author  
1. Guo L, Zhu C, Cai L, Zhang X, Fang Y, **Chen H**, Yang H. Global burden of lung cancer in 2022 and projected burden in 2050. Chin Med J (Engl). 2024 Nov 5;137(21):2577-2582.
2. Wang M, **Chen H**, Wong MCS, Huang J, Jin Y, Zheng ZJ. Effects of screening coverage and screening quality assurance on cervical cancer mortality: Implication for integrated framework to monitor global implementation of cervical cancer screening programmes. J Glob Health. 2024 Oct 25;14:04189.

### 2022-2023
> leading author

1. **Chen H#**, Shi J#, Lu M, Li Y, Du L, Liao X, Wei D, Dong D, Gao Y, Zhu C, Ying R, Zheng W, Yan S, Xiao H, Zhang J, Kong Y, Li F, Zou S, Liu C, Wang H, Zhang Y, Lu B, Luo C, Cai J, Tian J, Miao X, Ding K, Brenner H, Dai M. Comparison of Colonoscopy, Fecal Immunochemical Test, and Risk-adapted Approach in a Colorectal Cancer Screening Trial (TARGET-C). *Clin Gastroenterol Hepatol*. 2023;21(3):808-818.
2. Zhang Y, **Chen H**, Lu M, Cai J, Lu B, Luo C, Dai M. Habitual Diet Pattern Associations with Gut Microbiome Diversity and Composition: Results from a Chinese Adult Cohort. *Nutrients*. 2022;14(13):2639.
3. **Chen H**, Lu B, Dai M. Colorectal Cancer Screening in China: Status, Challenges, and Prospects - China, 2022. *China CDC Wkly*. 2022;4(15):322-328.
4. Lu B, Wang L, Lu M, Zhang Y, Cai J, Luo C, **Chen H**, Dai M. Microsimulation Model for Prevention and Intervention of Coloretal Cancer in China (MIMIC-CRC): Development, calibration, validation, and application. *Front Oncol*. 2022;12:883401.
5. Luo C#, Wang L#, Zhang Y, Lu M, Lu B, Cai J, **Chen H**, Dai M. Advances in breast cancer screening modalities and status of global screening programs. *Chronic Dis Transl Med*. 2022;1-12.
6. Wang L, **Chen H#**, Zhu Y, Lu M, Wang Y, Chen X, Ma W, Du L, Chen W. One-sample quantitative and two-sample qualitative faecal immunochemical tests for colorectal cancer screening: a cross-sectional study in China. *BMJ Open*. 2022;12(5):e059754.
7. Lu M, Zhang Y, Cai J, Lu B, Luo C, **Chen H**, Dai M. Head-to-head comparison of a risk-adapted screening strategy using various risk prediction models in detecting colorectal neoplasm. *J Gastroenterol Hepatol*. 2022;37(7):1244-1252.
8. Cai J, **Chen H#**, Lu M, Zhang Y, Lu B, Luo C, Feng X, You L, Dai M, Zhao Y. Association between Temporal Glycemic Change and Risk of Pancreatic Cancer in Men: A Prospective Cohort Study. Cancers (Basel). 2022 Jul 13;14(14):3403.
9. Luo C, Li N, Lu B, Cai J, Lu M, Zhang Y, **Chen H**, Dai M. Global and regional trends in incidence and mortality of female breast cancer and associated factors at national level in 2000 to 2019. *Chin Med J (Engl)*. 2022;135(1):42-51.
> contributting author  

1. Song S, Pei L, **Chen H**, Zhang Y, Sun C, Yi J, Huang Y. Analysis of hospital and payer costs of care: aggressive warming versus routine warming in abdominal major surgery. Front Public Health. 2023 Nov 2;11:1256254.
2. Chen C, Cai Y, Liu Y, Chen S, Li Y, Zhang F, Zhang M, Lu Z, Ying P, Huang J, Fan L, Cai X, Ning C, Wang W, Jiang Y, Zhang H, Yang S, Wang Z, Wang X, Zhang S, Huang C, Xu B, Fu Z, Song Q, Jin M, Chen K, **Chen H**, Dai M, Miao X, Yang X, Zhu Y, Tian J. Pan-Cancer Analysis of Microbiome Quantitative Trait Loci. Cancer Res. 2022 Oct 4;82(19):3449-3456.
3. Wu Z, Tan F, Yang Z, Wang F, Cao W, Qin C, Dong X, Zheng Y, Luo Z, Zhao L, Yu Y, Xu Y, Ren J, Shi J, **Chen H**, Li J, Tang W, Shen S, Wu N, Chen W, Li N, He J. Sex disparity of lung cancer risk in non-smokers: a multicenter population-based prospective study based on China National Lung Cancer Screening Program. Chin Med J (Engl). 2022 Jun 5;135(11):1331-1339.
4. Wu Z, Xie S, Wang F, Chen S, Su K, Li F, Cui H, Cao W, Yu Y, Qin C, Zheng Y, Dong X, Yang Z, Luo Z, Zhao L, Xu Y, Chen H, Li J, Wang G, Wu S, Dai M, Li N, He J. BMI changes and the risk of lung cancer in male never-smokers: A prospective cohort study. Cancer Med. 2022 Mar;11(5):1336-1346.

### 2020-2021
> leading author

1. Li N#, Lu B#, Luo C, Cai J, Lu M, Zhang Y, **Chen H**, Dai M. Incidence, mortality, survival, risk factor and screening of colorectal cancer: A comparison among China, Europe, and northern America. *Cancer Lett*. 2021;522:255-268. 
2. Cai J#, **Chen H#**, Lu M, Zhang Y, Lu B, You L, Zhang T, Dai M, Zhao Y. Advances in the epidemiology of pancreatic cancer: Trends, risk factors, screening, and prognosis. *Cancer Lett*. 2021;520:1-11.   
3. **Chen H#**, Liu L#, Lu M, Zhang Y, Lu B, Zhu Y, Tian J, Li X, Nie S, Miao X, Dai M. Implications of Lifestyle Factors and Polygenic Risk Score for Absolute Risk Prediction of Colorectal Neoplasm and Risk-Adapted Screening. *Front Mol Biosci*. 2021;8:685410.
4. **Chen H#**, Wang L, Lu M, Zhu C, Zhu Y, Ma W, Chen X, Du L, Chen W. Comparative yield and efficiency of strategies based on risk assessment and fecal immunochemical test in colorectal cancer screening: A cross-sectional population-based analysis. *Chin J Cancer Res*. 2021;33(4):512-521. 
5. Zhang Y, Lu M, Lu B, Liu C, Ma Y, Liu L, Miao X, Qin J, **Chen H**, Dai M. Leveraging Fecal Microbial Markers to Improve the Diagnostic Accuracy of the Fecal Immunochemical Test for Advanced Colorectal Adenoma. *Clin Transl Gastroenterol*. 2021;12(8):e00389.
6. Lu M, Wang L, Zhang Y, Liu C, Lu B, Du L, Liao X, Dong D, Wei D, Gao Y, Shi J, Ren J, **Chen H**, Dai M. Optimizing Positivity Thresholds for a Risk-Adapted Screening Strategy in Colorectal Cancer Screening. *Clin Transl Gastroenterol*. 2021;12(8):e00398.
7. Lu M, Zhang YH, Lu B, Cai J, Liu CC, **Chen H**, Dai M. Head-to-head comparison of the test performance of self-administered qualitative vs. laboratory-based quantitative fecal immunochemical tests in detecting colorectal neoplasm. *Chin Med J (Engl)*. 2021;134(11):1335-1344. 
8. Lu B#, Li N#, Luo CY, Cai J, Lu M, Zhang YH, **Chen H**, Dai M. Colorectal cancer incidence and mortality: the current status, temporal trends and their attributable risk factors in 60 countries in 2000-2019. *Chin Med J (Engl)*. 2021;134(16):1941-1951. 
9. **Chen H**, Lu M, Zhang YH, Dai M*. Divergent detection rates of fecal immunochemical test and questionnaire-based risk assessment for detecting proximal and distal advanced colorectal adenomas. *Chin Med J (Engl)*. 2021;134(5):605-607.
10. **Chen H**, Lu M, Liu C, Zou S, Du L, Liao X, Dong D, Wei D, Gao Y, Zhu C, Zhu L, Zheng W, Xiao H, Kong Y, Yin H, Zhou H, Ying R, Wang B, Zhang J, Zhang X, Zhang Q, Zhang X, Zhang Y, Wang H, Guo L, Liu L, Ren J, Shi J, Li N, Miao X, Brenner H, Dai M. Comparative Evaluation of Participation and Diagnostic Yield of Colonoscopy vs Fecal Immunochemical Test vs Risk-Adapted Screening in Colorectal Cancer Screening: Interim Analysis of a Multicenter Randomized Controlled Trial (TARGET-C). *Am J Gastroenterol*. 2020;115(8):1264-1274. 
11. Wang H, Zhang B, Li X, Zhou D, Li Y, Jia S, Qi S, Xu A, Zhao X, Wang J, Bai Z, Cao B, Li N, Dai M, **Chen H**, Huang J. Identification and Validation of Novel Serum Autoantibody Biomarkers for Early Detection of Colorectal Cancer and Advanced Adenoma. *Front Oncol*. 2020;10:1081.
> contributting author

1. Wang H, Zhu Y, **Chen H**, Yang N, Wang X, Li B, Ying P, He H, Cai Y, Zhang M, Niu S, Li Y, Lu Z, Peng X, Zou D, Zhong R, Chang J, Dai M, Tian J, Miao X. Colorectal cancer risk variant rs7017386 modulates two oncogenic lncRNAs expression via ATF1-mediated long-range chromatin loop. Cancer Lett. 2021 Oct 10;518:140-151.
2. Cao M, Li H, Sun D, He S, Yu Y, Li J, **Chen H**, Shi J, Ren J, Li N, Chen W. Cancer screening in China: The current status, challenges, and suggestions. Cancer Lett. 2021 May 28;506:120-127. 
3. Li J, Hu P, Shi J, Fan Y, Ren J, **Chen H**, Li N, Liao X, Liu Y, Du L, Wu N, Tang W, Zhang Y, Zou S, Pinsky P, Prorok P, Fagerstrom R, Taylor M, Kramer B, Dai M, He J; China Cancer Screening Trial Feasibility Study Group. Results of the cancer screening feasibility study in China: a multicentered randomized controlled trial of lung and colorectal cancer screening. J Natl Cancer Cent. 2021 Jul 31;1(4):132-138. (IF=9.4)
4. Song S, Duan Y, Huang J, Wong MCS, **Chen H**, Trisolini MG, Labresh KA, Smith SC Jr, Jin Y, Zheng ZJ. Socioeconomic Inequalities in Premature Cancer Mortality Among U.S. Counties During 1999 to 2018. Cancer Epidemiol Biomarkers Prev. 2021 Jul;30(7):1375-1386.
5. Feng X, Wang G, Lyu Z, Chen S, Wei L, Li X, Wen Y, Chen Y, Xie S, Cui H, **Chen H** Li J, Lin C, Ren J, Shi J, Wu S, Dai M, Li N, He J. The association between fasting blood glucose trajectory and cancer risk in Chinese population without diabetes. Int J Cancer. 2020 Aug 15;147(4):958-966.
6. Lyu Z, Li N, Chen S, Wang G, Tan F, Feng X, Li X, Wen Y, Yang Z, Wang Y, Li J, **Chen H**, Lin C, Ren J, Shi J, Wu S, Dai M, He J. Risk prediction model for lung cancer incorporating metabolic markers: Development and internal validation in a Chinese population. Cancer Med. 2020 Jun;9(11):3983-3994.
7. Guo L, **Chen H**, Wang G, Lyu Z, Feng X, Wei L, Li X, Wen Y, Lu M, Chen Y, Shi J, Ren J, Lin C, Yu X, Chen S, Wu S, Li N, Dai M, He J. Development of a risk score for colorectal cancer in Chinese males: A prospective cohort study. Cancer Med. 2020 Jan;9(2):816-823.

### 2018-2019
> leading author

1. **Chen H#**, Li N#, Ren J, Feng X, Lyu Z, Wei L, Li X, Guo L, Zheng Z, Zou S, Zhang Y, Li J, Zhang K, Chen W, Dai M, He J. Participation and yield of a population-based colorectal cancer screening programme in China. *Gut*. 2019;68(8):1450-1457.  
2. Wang Y#, **Chen H#**, Li N, Ren J, Zhang K, Dai M, He J. Ultrasound for Breast Cancer Screening in High-Risk Women: Results From a Population-Based Cancer Screening Program in China. *Front Oncol*. 2019;9:286.  
3. Lu M, Luo X, Li N, **Chen H**, Dai M. Diagnostic Accuracy of Fecal Occult Blood Tests For Detecting Proximal Versus Distal Colorectal Neoplasia: A Systematic Review And Meta-Analysis. *Clin Epidemiol*. 2019;11:943-954.   
4. **Chen H#**, Li N#, Shi J, Ren J, Liu C, Zhang Y, Jiang Z, Zhang Z, Dai M. Comparative evaluation of novel screening strategies for colorectal cancer screening in China (TARGET-C): a study protocol for a multicentre randomised controlled trial. *BMJ Open*. 2019;9(4):e025935.
5. **Chen H#**, Zhang Y#, Li S, Li N, Chen Y, Zhang B, Qu C, Ding H, Huang J, Dai M. Direct comparison of five serum biomarkers in early diagnosis of hepatocellular carcinoma. *Cancer Manag Res*. 2018 Jul 10;10:1947-1958.  
6. Li S, Li X, Xu A, Zhang B, He X, **Chen H**, Huang J. Screening and clinical evaluation of dominant peptides of centromere protein F antigen for early diagnosis of hepatocellular carcinoma. *Mol Med Rep*. 2018 Mar;17(3):4720-4728. 
> contributting author  

1. Tang W, Peng Q, Lyu Y, Feng X, Li X, Wei L, Li N, **Chen H**, Chen W, Dai M, Wu N, Li J, Huang Y. Risk prediction models for lung cancer: Perspectives and dissemination. Chin J Cancer Res. 2019 Apr;31(2):316-328.
2. Lyu Z, Li N, Wang G, Feng X, Chen S, Su K, Li F, Wei L, Li X, Xie S, Guo L, Chen Y, Tan F, Yin J, Cui H, **Chen H**, Li J, Ren J, Shi J, Wu S, Dai M, He J. Independent and joint associations of blood lipids and lipoproteins with lung cancer risk in Chinese males: A prospective cohort study. Int J Cancer. 2019 Jun 15;144(12):2972-2984.
3. Li X, **Chen H**, Wang G, Feng X, Lyu Z, Wei L, Wen Y, Chen S, Wu S, Hang D, Dai M, Li N, He J. Metabolic Syndrome Components and the Risk of Colorectal Cancer: A Population-Based Prospective Study in Chinese Men. Front Oncol. 2019 Oct 17;9:1047.
4. Guo L, **Chen H**, Wang G, Lyu Z, Feng X, Wei L, Li X, Wen Y, Lu M, Chen Y, Shi J, Ren J, Lin C, Yu X, Chen S, Wu S, Li N, Dai M, He J. Development of a risk score for colorectal cancer in Chinese males: A prospective cohort study. Cancer Med. 2020 Jan;9(2):816-823.
5. Wei L, Li N, Wang G, Feng X, Lyu Z, Li X, Wen Y, Chen Y, **Chen H**, Chen S, Wu S, Dai M, He J. Waist Circumference Might Be a Predictor of Primary Liver Cancer: A Population-Based Cohort Study. Front Oncol. 2018 Dec 12;8:607.

### 2014-2017
> leading author

1. **Chen H**, Werner S, Brenner H. Fresh vs Frozen Samples and Ambient Temperature Have Little Effect on Detection of Colorectal Cancer or Adenomas by a Fecal Immunochemical Test in a Colorectal Cancer Screening Cohort in Germany. *Clin Gastroenterol Hepatol*. 2017;15(10):1547-1556.e5.  
2. **Chen H**, Qian J, Werner S, Cuk K, Knebel P, Brenner H*. Development and validation of a panel of five proteins as blood biomarkers for early detection of colorectal cancer. *Clin Epidemiol*. 2017;9:517-526.
3. **Chen H**, Knebel P, Brenner H. Empirical evaluation demonstrated importance of validating biomarkers for early detection of cancer in screening settings to limit the number of false-positive findings. *J Clin Epidemiol*. 2016;75:108-14. 
4. **Chen H**, Zucknick M, Werner S, Knebel P, Brenner H. Head-to-Head Comparison and Evaluation of 92 Plasma Protein Biomarkers for Early Detection of Colorectal Cancer in a True Screening Setting. *Clin Cancer Res*. 2015;21(14):3318-26.
5. **Chen H**, Chen XZ, Waterboer T, Castro FA, Brenner H. Viral infections and colorectal cancer: a systematic review of epidemiological studies. *Int J Cancer*. 2015;137(1):12-24. 
6. **Chen H**, Werner S, Tao S, Zörnig I, Brenner H. Blood autoantibodies against tumor-associated antigens as biomarkers in early detection of colorectal cancer. *Cancer Lett*. 2014;346(2):178-87.
7. Peng C, **Chen H#**, Wallwiener M, Modugno C, Cuk K, Madhavan D, Trumpp A, Heil J, Marmé F, Nees J, Riethdorf S, Schott S, Sohn C, Pantel K, Schneeweiss A, Yang R, Burwinkel B. Plasma S100P level as a novel prognostic marker of metastatic breast cancer. Breast Cancer Res Treat. 2016 Jun;157(2):329-338.
> contributting author

1. Feng X, Wang G, Li N, Lyu Z, Chen S, Wei L, Chen Y, Xie S, Yang W, Yin J, Cui H, **Chen H**, Ren J, Shi J, Wu S, Dai M, He J. The association between fasting blood glucose and the risk of primary liver cancer in Chinese males: a population-based prospective study. Br J Cancer. 2017 Oct 24;117(9):1405-1411.
2. Brenner H, Niedermaier T, **Chen H**. Strong subsite-specific variation in detecting advanced adenomas by fecal immunochemical testing for hemoglobin. Int J Cancer. 2017 May 1;140(9):2015-2022.
3. Brenner H, **Chen H**. Fecal occult blood versus DNA testing: indirect comparison in a colorectal cancer screening population. Clin Epidemiol. 2017 Jul 13;9:377-384.
4. Werner S, Krause F, Rolny V, Strobl M, Morgenstern D, Datz C, **Chen H**, Brenner H. Evaluation of a 5-Marker Blood Test for Colorectal Cancer Early Detection in a Colorectal Cancer Screening Setting. Clin Cancer Res. 2016 Apr 1;22(7):1725-33.
5. Werner S, **Chen H**, Butt J, Michel A, Knebel P, Holleczek B, Zörnig I, Eichmüller SB, Jäger D, Pawlita M, Waterboer T, Brenner H. Evaluation of the diagnostic value of 64 simultaneously measured autoantibodies for early detection of gastric cancer. Sci Rep. 2016 May 3;6:25467.
6. Werner S, **Chen H**, Tao S, Brenner H. Systematic review: serum autoantibodies in the early detection of gastric cancer. Int J Cancer. 2015 May 15;136(10):2243-52.
7. Chen XZ, **Chen H**, Castro FA, Hu JK, Brenner H. Epstein-Barr virus infection and gastric cancer: a systematic review. Medicine (Baltimore). 2015 May;94(20):e792.